import { create } from "zustand";

export const useV2boardUserData = create((set) => ({
  isLoading: false,
  registerData: {},
  infoData: {},
  subscribeData: {},
  trafficLogData: {},
  serverFetchData: {},
  configData: {},
  botInfoData: {},
  orderFetchData: {},
  inviteDetailsData: {},
  inviteFetchData: {},
  planFetchData: {},
  planActive: 1,
  planFetchIDData: {},
  orderDetailData: {},
  orderPaymentMethodData: {},
  knowledgeFetchData: {},
  knowledgeFetchIDData: {},
  knowledgeActive: false,
  ticketFetchData: {},
  ticketFetchIDData: {},

  setIsLoading: (value: any) => set({ isLoading: value }),
  setRegisterData: (data: any) => set({ registerData: data }),
  setInfoData: (data: any) => set({ infoData: data }),
  setSubscribeData: (data: any) => set({ subscribeData: data }),
  setTrafficLogData: (data: any) => set({ trafficLogData: data }),
  setServerFetchData: (data: any) => set({ serverFetchData: data }),
  setConfigData: (data: any) => set({ configData: data }),
  setBotInfoData: (data: any) => set({ botInfoData: data }),
  setOrderFetchData: (data: any) => set({ orderFetchData: data }),
  setInviteDetailsData: (data: any) => set({ inviteDetailsData: data }),
  setInviteFetchData: (data: any) => set({ inviteFetchData: data }),
  setPlanFetchData: (data: any) => set({ planFetchData: data }),
  setPlanActive: (value: any) => set({ planActive: value }),
  setPlanFetchIDData: (data: any) => set({ planFetchIDData: data }),
  setOrderDetailData: (data: any) => set({ orderDetailData: data }),
  setOrderPaymentMethodData: (data: any) =>
    set({ orderPaymentMethodData: data }),
  setKnowledgeFetchData: (data: any) => set({ knowledgeFetchData: data }),
  setKnowledgeFetchIDData: (data: any) => set({ knowledgeFetchIDData: data }),
  setKnowledgeActive: (value: any) => set({ knowledgeActive: value }),
  setTicketFetchData: (data: any) => set({ ticketFetchData: data }),
  setTicketFetchIDData: (data: any) => set({ ticketFetchIDData: data }),
}));
